### ISSUE TITLE
error in from_kml function

### ISSUE THREAD

**Issue by szwang1990** [FESOM/fmesh#8]
I followed the guidance, downloaded the main branch and all needed files and modified configure.yml a little bit. When I run `python fmesh.py`, the following error was reported:

```
[0.0, -5.0, -10.0, -15.0, -20.0, -25.0, -30.0, -35.0, -40.0, -45.0, -50.0, -55.0, -60.0, -65.0, -70.0, -75.0, -80.0, -85.0, -90.0, -95.0, -100.0, -110.0, -120.0, -130.0, -140.0, -150.0, -160.0, -170.0, -180.0, -190.0, -200.0, -220.0, -240.0, -260.0, -280.0, -300.0, -340.0, -380.0, -420.0, -460.0, -500.0, -540.0, -580.0, -620.0, -660.0, -760.0, -860.0, -1040.0, -1180.0, -1380.0, -1500.0, -1700.0, -1920.0, -2150.0, -2400.0, -2650.0, -2900.0, -3150.0, -3400.0, -3650.0, -3900.0, -4150.0, -4400.0, -4650.0, -4900.0, -5150.0, -5400.0, -5650.0, -6000.0, -6350.0]
Traceback (most recent call last):
  File "/home/swang/Data/code/codeLib/fromOthers/Python/fmesh/fmesh-main/fmesh.py", line 990, in <module>
    main()
  File "/home/swang/Data/code/codeLib/fromOthers/Python/fmesh/fmesh-main/fmesh.py", line 975, in main
    result, regions, longitudes, latitudes = define_resolutions(settings)
  File "/home/swang/Data/code/codeLib/fromOthers/Python/fmesh/fmesh-main/fmesh.py", line 574, in define_resolutions
    internal, outer = from_kml( reg["path"] )
  File "/home/swang/Data/code/codeLib/fromOthers/Python/fmesh/fmesh-main/fmesh.py", line 211, in from_kml
    np.vsplit(np.array(feature_2.geometry.coords.xy), 2)
AttributeError: 'tuple' object has no attribute 'xy'
```

I tried the Baffin_Bay.kml file in the kml directory, and also tried to generate my own kml file using google earth. In line 211 of fmesh.py, it seemed to me that there is no an attribute named xy in feature_2.geometry.coords.

I also tried the new `afterser `branch, the same error occurred.

**Comment by Sealki** [comment]
Hello there,

Thank you for reporting this issue. Although I have no idea what the
problem with .kml file could be, I will have a look into this later this
week.

There have not been any issues with any of the different .kml files I used
to create my test or working meshes before.

Regards,
Sergei

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by szwang1990** [comment]
Hi Sergei,

Thanks for the reply. I tried different `kml `files, and also tried my own `kml `file. The same error occurs.

Best,
Shizhu

**Comment by Sealki** [comment]
Hi Shizhu,

It sounds really strange since the test .kml files stored in github had
previously been used for creating meshes.
Could it be that the problem is with the fastkml module installed on your
computer? Can you re-instal the latest version and give it another try?

The best,
Sergei

**Comment by szwang1990** [comment]
Hi Sergei,

I install all modules using the `requirements.yml` file. I double checked the version of `fastkml `and it is 0.12.
Here I attach one test file, and you can see the error occurs when the code looks for an nonexistent attribute.

[test_fastkml.zip](https://github.com/FESOM/fmesh/files/10979781/test_fastkml.zip)

Best
Shizhu

**Comment by Sealki** [comment]
Hi Shizhu,

Well... I still don't understand why such issue occurs. I have the same version of _fastkml_ (0.12) and the program works fine with .kml files from the /test. The only difference is that my calling _feature_2.geometry.coords_ returns an _shapely.coords.CoordinateSequence_ object in memory and it is _.xy_ attribute that allows to get latitude and longitude data stored in .kml file. But in your case the _feature_2.geometry.coords_ returns an array with longitudes and latitudes right away. I may suspect, that the reason is in a version of _shapely_ module. I have v.1.7.1, whereas your version is 2.0.1.  

So, to solve this problem you can either try using an older _shapely_ version, or modify your code a bit: 
1) to get rid of _.xy_ attribute in the problematic line, and
2) alter that line appropriately to unpack your _feature_2.geometry.coords_ array into longitude and latitudes.

I hope it will help.
Sergei

**Comment by szwang1990** [comment]
Hi Sergei,

I modified the fmesh.py file a little bit as you suggested, now it works well. Thanks so much for your help.

Best,
Shizhu

**Comment by Sealki** [comment]
Hi Shizhu,
I am glad you could make it working!
The best,
Sergei
